apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: db-init
          image: nginx
          command: ["sh", "-c", "echo inittttttttttttttt; sleep 60"]
      restartPolicy: Never
