apiVersion: batch/v1
kind: Job
metadata:
  name: start-statefulset
  annotations:
    "argocd.argoproj.io/hook": PostSync
spec:
  template:
    spec:
      containers:
        - name: db-upgrade
          image: nginx
          command: ["sh", "-c", "echo starting sts; sleep 60"]
      restartPolicy: Never
